services:
  mysql:
    image: mysql:8.4.5
    ports:
      - 3306:3306
    volumes_from:
      - dbdata
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: development

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  web:
    build: .
    environment:
      RAILS_ENV: development
      RUBY_DEBUG_OPEN: true
      RUBY_DEBUG_HOST: 0.0.0.0
      RUBY_DEBUG_PORT: 8888
      SELENIUM_REMOTE_HOST: chrome
      SELENIUM_REMOTE_PORT: 4444
    ports:
      - 3000:3000
      - 8888:8888
    volumes_from:
      - webdata
    depends_on:
      - mysql
      - chrome

  webdata:
    image: tianon/true
    volumes:
      - ".:/workspace"
  
  chrome:
    image: selenium/standalone-chrome
    environment:
      SE_VNC_NO_PASSWORD: true
      VNC_NO_PASSWORD: true
      SCREEN_WIDTH: 1500
      SCREEN_HEIGHT: 900
    ports:
      - 4444:4444
      - 7900:7900